/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fit_vutbr_faceswap_CameraPreview_SavePhotoTask */

#ifndef _Included_fit_vutbr_faceswap_CameraPreview_SavePhotoTask
#define _Included_fit_vutbr_faceswap_CameraPreview_SavePhotoTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
