/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fit_vutbr_faceswap_CameraPreview */

#ifndef _Included_fit_vutbr_faceswap_CameraPreview
#define _Included_fit_vutbr_faceswap_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fit_vutbr_faceswap_CameraPreview
 * Method:    kalmanFilterNative
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_fit_vutbr_faceswap_CameraPreview_kalmanFilterNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     fit_vutbr_faceswap_CameraPreview
 * Method:    extractLuminanceNative
 * Signature: ([BIIII[I)V
 */
JNIEXPORT void JNICALL Java_fit_vutbr_faceswap_CameraPreview_extractLuminanceNative
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jintArray);

/*
 * Class:     fit_vutbr_faceswap_CameraPreview
 * Method:    applyGrayScale
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_fit_vutbr_faceswap_CameraPreview_applyGrayScale
  (JNIEnv *, jobject, jbyteArray, jint, jint, jintArray);

/*
 * Class:     fit_vutbr_faceswap_CameraPreview
 * Method:    toRGB565
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_fit_vutbr_faceswap_CameraPreview_toRGB565
  (JNIEnv *, jobject, jbyteArray, jint, jint, jintArray);

/*
 * Class:     fit_vutbr_faceswap_CameraPreview
 * Method:    processImage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_fit_vutbr_faceswap_CameraPreview_processImage
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
